# Generated by Django 6.0.5 on 2026-05-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_order_quantity_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Diproses', 'Diproses'), ('Berhasil', 'Berhasil'), ('Ditolak', 'Ditolak')], default='Pending', max_length=20),
        ),
    ]
